{{- if .Values.ingress.tls -}}
{{- $fullName := include "konker-registry-helm.fullname" . -}}
{{- range .Values.ingress.tls }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .secretName }}
  spec:
    secretName: {{ .secretName }}
    issuerRef:
      name: letsencrypt-stg
    commonName: {{ .commonName }}
    dnsNames:
    {{- range .hosts }}
      - {{ . | quote }}
    {{- end }}
    acme:
      config:
      - http01:
          ingressClass: nginx
        domains:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}          
      - http01:
          ingress: api
        domains:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
{{- end }}
{{- end }}
---
